provider:
  name: aws
  runtime: nodejs14.x
  lambdaHashingVersion: '20240801'
  region: us-east-1
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:PutItem
            - dynamodb:UpdateItem
            - dynamodb:GetItem
            - dynamodb:scan
          Resource:
            - arn:aws:dynamodb:us-east-1:table/ItemTableNew

functions:
  hello:
    handler: src/handler.hello
    events:
      -http:
        path: /
        method: get
  insertItem:
    handler: src/insert.handler
    events:
      -http:
        path: /item
        method: get
  fetchItem:
    handler: src/fetchItem.handler
    events:
      -http:
        path: /items/{id}
        method: get
  fetchItem:
    handler: src/fetchItem.handler
    events:
      -http:
        path: /items/{id}
        method: put
  fetchItems:
    handler: src/fetchItems.handler
    events:
      -http:
        path: /items
        method: get

resources:
  Resources:
    ItemTableNew:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ItemTableNew
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: id
          - AttributeType: S
        KeySchema:
          - AttributeName: id
          - keyType: HASH